<a href="https://colab.research.google.com/github/SchimeNo/Deep-Learning-with-Python/blob/main/02_The_mathematical_building_blocks_of_neural_networks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **02 The mathematical building blocks of neural networks** 
---


In [ ]:
#!pip install keras
from keras.datasets import mnist

In [ ]:
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

11493376/11490434 [==============================] - 0s 0us/step


In [ ]:
print("Shape:", train_images.shape,"Length:", len(train_labels),"Array:", train_labels,sep="\n")

Shape:
(60000, 28, 28)
Length:
60000
Array:
[5 0 4 ... 5 6 8]


In [ ]:
print("Shape:", test_images.shape,"Length:", len(test_labels),"Array:", test_labels,sep="\n")

Shape:
(10000, 28, 28)
Length:
10000
Array:
[7 2 1 ... 4 5 6]


## Network architecture

**Loss function:**
-  How the network will be able to measure its performance on
the training data, and thus how it will be able to steer itself in the right direction.

**Optimizer:**
- The mechanism through which the network will update itself
based on the data it sees and its loss function.

**Metrics:**
- Here, we’ll only care about accuracy (the fraction of the images that were correctly classified).



In [ ]:
# Network architecture

from keras import models
from keras import layers

network = models.Sequential()
network.add(layers.Dense(512, activation='relu', input_shape=(28*28,)))
network.add(layers.Dense(10, activation='softmax'))


### The compilation step (optimizer, loss, metric)

In [ ]:
network.compile(optimizer='rmsprop',
                loss='categorical_crossentropy',
                metrics=['accuracy'])

### Preparing the image data

We’ll transform the data into a float32 array of shape (60000, 28 * 28) with values between 0 and 1


In [ ]:
train_images = train_images.reshape((60000, 28*28))
train_images = train_images.astype('float32')/255

test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype('float32') / 255

### Preparing the labels

In [ ]:
from keras.utils import to_categorical

train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

###Train the network


In [ ]:
network.fit(train_images, train_labels, epochs=5, batch_size=128)

Epoch 1/5
469/469 [==============================] - 5s 9ms/step - loss: 0.4253 - accuracy: 0.8782
Epoch 2/5
469/469 [==============================] - 4s 9ms/step - loss: 0.1139 - accuracy: 0.9659
Epoch 3/5
469/469 [==============================] - 4s 9ms/step - loss: 0.0703 - accuracy: 0.9785
Epoch 4/5
469/469 [==============================] - 5s 10ms/step - loss: 0.0483 - accuracy: 0.9845
Epoch 5/5
469/469 [==============================] - 4s 10ms/step - loss: 0.0361 - accuracy: 0.9895


### Use on test set

In [ ]:
test_loss, test_acc = network.evaluate(test_images, test_labels)
print('test_acc:', test_loss)

313/313 [==============================] - 1s 2ms/step - loss: 0.0664 - accuracy: 0.9796
test_acc: 0.06635305285453796


# Data representations for neural networks

### Tensors

Data stored in multidimensional Numpy arrays. It's a container for data—almost always numerical data. So, it’s a
container for numbers. You may be already familiar with matrices, which are 2D tensors: tensors are a generalization of matrices to an arbitrary number of dimensions
(note that in the context of tensors, a dimension is often called an axis).



#### Scalars (0D tensors)
A tensor that contains only one number is called a scalar

In [ ]:
import numpy as np
x=np.array(12)
print(x,"\ndim:", x.ndim)

12 
dim: 0


#### Vectors

In [16]:
x = np.array([12, 3, 6, 14])
print(x,"\ndim:", x.ndim)

[12  3  6 14] 
dim: 1


#### Matrices (2D tensors)